# Generated by Django 4.2.16 on 2024-11-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_policy_created_by_remove_policy_modified_by_and_more'),
        ('users', '0002_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='policies',
        ),
        migrations.AddField(
            model_name='account',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='accounts', related_query_name='account', to='security.module', verbose_name='Permissions'),
        ),
    ]
