# Generated by Django 4.2.16 on 2024-11-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_policies_account_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='DNI'),
        ),
    ]
