# Generated by Django 4.2.16 on 2024-11-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Comments'),
        ),
    ]
