# Generated by Django 4.2.16 on 2024-11-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Phone'),
        ),
    ]
