# Generated by Django 4.2.19 on 2025-03-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_client_created_by_client_modified_by_client_modules_and_more'),
        ('users', '0006_alter_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='omic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.omic', verbose_name='Omic'),
        ),
    ]
