# Generated by Django 4.2.20 on 2025-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_account_omic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='support_level',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='Support Level'),
        ),
    ]
