# Generated by Django 4.2.16 on 2024-09-05 11:24

import administration.models
from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at (UTC)')),
                ('created_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Created from (IP)')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at (UTC)')),
                ('modified_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Modified from (IP)')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=administration.models.get_logo_path, verbose_name='Logo')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone')),
                ('address', models.TextField(blank=True, default='', verbose_name=' Address')),
                ('cant_students', models.IntegerField(blank=True, default=0, verbose_name='Cant Students')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
    ]
