# Generated by Django 4.2.19 on 2025-03-03 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_delete_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_account_phone'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='client',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='client',
            name='modules',
            field=models.ManyToManyField(blank=True, to='security.module', verbose_name='Modules'),
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_owner', to='users.account', verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='TrafficLightSystemTimes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at (UTC)')),
                ('created_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Created from (IP)')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at (UTC)')),
                ('modified_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Modified from (IP)')),
                ('greenToYellow_c', models.IntegerField(blank=True, default=0, verbose_name='Green To Yellow Common')),
                ('yellowToRed_c', models.IntegerField(blank=True, default=0, verbose_name='Yellow to Red Common')),
                ('greenToYellow_ive_hv', models.IntegerField(blank=True, default=0, verbose_name='Green To Yellow IVE and HV')),
                ('yellowToRed_ive_hv', models.IntegerField(blank=True, default=0, verbose_name='Yellow to Red IVE and HV')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'TrafficLightSystemTime',
                'verbose_name_plural': 'TrafficLightSystemTimes',
            },
        ),
        migrations.CreateModel(
            name='Omic',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at (UTC)')),
                ('created_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Created from (IP)')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at (UTC)')),
                ('modified_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Modified from (IP)')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('responsible', models.CharField(max_length=255, verbose_name='Responsible')),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='Opening Hours')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Omic',
                'verbose_name_plural': 'Omics',
            },
        ),
    ]
