# Generated by Django 4.2.16 on 2025-01-08 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLightSystemTimes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at (UTC)')),
                ('created_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Created from (IP)')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at (UTC)')),
                ('modified_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Modified from (IP)')),
                ('greenToYellow', models.IntegerField(blank=True, default=0, verbose_name='Green To Yellow')),
                ('yellowToRed', models.IntegerField(blank=True, default=0, verbose_name='Yellow to Red')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'TrafficLightSystemTime',
                'verbose_name_plural': 'TrafficLightSystemTimes',
            },
        ),
    ]
