# Generated by Django 4.2.18 on 2025-01-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_trafficlightsystemtimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlightsystemtimes',
            name='greenToYellow',
        ),
        migrations.RemoveField(
            model_name='trafficlightsystemtimes',
            name='yellowToRed',
        ),
        migrations.AddField(
            model_name='trafficlightsystemtimes',
            name='greenToYellow_c',
            field=models.IntegerField(blank=True, default=0, verbose_name='Green To Yellow Common'),
        ),
        migrations.AddField(
            model_name='trafficlightsystemtimes',
            name='greenToYellow_ive_hv',
            field=models.IntegerField(blank=True, default=0, verbose_name='Green To Yellow IVE and HV'),
        ),
        migrations.AddField(
            model_name='trafficlightsystemtimes',
            name='yellowToRed_c',
            field=models.IntegerField(blank=True, default=0, verbose_name='Yellow to Red Common'),
        ),
        migrations.AddField(
            model_name='trafficlightsystemtimes',
            name='yellowToRed_ive_hv',
            field=models.IntegerField(blank=True, default=0, verbose_name='Yellow to Red IVE and HV'),
        ),
    ]
