# Generated by Django 4.2.18 on 2025-02-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_omic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omic',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='omic',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
    ]
