openapi: 3.0.0
info:
  title: PDAC (Proyecto Defensa al Consumidor)
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local server
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Authentication
paths:
  /auth/v1/login/:
    post:
      tags:
        - Authentication
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: correo@prueba.com
                password: password
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}