# Generated by Django 4.2.18 on 2025-02-23 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claimer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at (UTC)')),
                ('created_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Created from (IP)')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at (UTC)')),
                ('modified_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Modified from (IP)')),
                ('fullname', models.CharField(max_length=255, verbose_name='Fullname')),
                ('dni', models.CharField(max_length=15, verbose_name='Dni')),
                ('cuit', models.CharField(max_length=20, verbose_name='Cuit/Cuil')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('gender', models.CharField(choices=[('x', 'X'), ('other', 'Otro'), ('male', 'Masculino'), ('none', 'Prefiero no decirlo'), ('female', 'Femenino')], max_length=10, verbose_name='Gender')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at (UTC)')),
                ('created_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Created from (IP)')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at (UTC)')),
                ('modified_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Modified from (IP)')),
                ('fullname', models.CharField(max_length=255, verbose_name='Fullname')),
                ('cuil', models.CharField(max_length=20, verbose_name='Cuil')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('num_address', models.CharField(blank=True, max_length=10, verbose_name='Num Address')),
                ('city_name', models.CharField(max_length=255, verbose_name='City/Provincie')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at (UTC)')),
                ('created_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Created from (IP)')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at (UTC)')),
                ('modified_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Modified from (IP)')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimRegular',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at (UTC)')),
                ('created_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Created from (IP)')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at (UTC)')),
                ('modified_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Modified from (IP)')),
                ('id', models.CharField(max_length=255, unique=True, verbose_name='Id')),
                ('comments', models.TextField(blank=True)),
                ('claim_access', models.CharField(blank=True, max_length=255, null=True, verbose_name='Claim Access')),
                ('type_of_claim', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of Claim')),
                ('claim_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Claim Status')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('heading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading')),
                ('subheading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subheading')),
                ('transfer_to_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transfer to company')),
                ('derived_to_omic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Derived to OMIC')),
                ('transfer_to_the_consumer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transfer to the consumer')),
                ('conciliation_hearing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conciliation hearing')),
                ('imputation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Imputation')),
                ('resolution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resolution')),
                ('monetary_agreement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Monetary Agreement')),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimer', to='claims.claimer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('files', models.ManyToManyField(to='claims.file')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('supplier', models.ManyToManyField(to='claims.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
