# Generated by Django 4.2.18 on 2025-02-24 00:28

import claims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='city_name',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='claimer',
            name='gender',
            field=models.CharField(choices=[('x', 'X'), ('other', 'Otro'), ('none', 'Prefiero no decirlo'), ('female', 'Femenino'), ('male', 'Masculino')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=claims.models.get_claim_image_path),
        ),
    ]
