# Generated by Django 4.2.19 on 2025-03-21 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_standardsandprotocols'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_account_omic'),
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimIVE',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at (UTC)')),
                ('created_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Created from (IP)')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at (UTC)')),
                ('modified_from', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Modified from (IP)')),
                ('id', models.CharField(max_length=255, unique=True, verbose_name='Id')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full Name')),
                ('dni', models.CharField(max_length=255, verbose_name='Dni')),
                ('birthdate', models.DateField(null=True, verbose_name='Birthdate')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('has_social_work', models.BooleanField(default=False, verbose_name='Has social work')),
                ('social_work_or_company', models.CharField(max_length=255, verbose_name='Social work or company')),
                ('establishment', models.CharField(max_length=255, verbose_name='Establishment')),
                ('other', models.CharField(max_length=255, verbose_name='Other')),
                ('reasons', multiselectfield.db.fields.MultiSelectField(choices=[('me_negaron_la_practica', 'Me negaron la práctica'), ('libertad_toma_decision', 'El personal de salud no respetó mi libertad en la toma de decisión'), ('turnos_medicos_plazo_dias', 'Me asignan turnos médicos y/o de estudios sin cumplir el plazo de días'), ('obstaculizan_atencion_medica', 'Me obstaculizan la atención médica'), ('sin_acceso_metodos_anticonceptivos', 'No me brindaron acceso a métodos anticonceptivos (posaborto)'), ('no_reintegraron_practica', 'No me reintegraron la práctica'), ('no_reintegraron_medicamentos', 'No me reintegraron los medicamentos'), ('no_suministraron_medicamentos', 'No me suministraron los medicamentos'), ('sin_atencion_posaborto', 'No tuve atención posaborto'), ('mas_de_10_dias_sin_respuesta', 'Pasaron más de 10 días sin respuesta desde que solicité la práctica'), ('dificultades_trato_personal', 'Tuve dificultades en el trato con el personal de salud'), ('otra', 'Otra')], max_length=255)),
                ('activity', models.JSONField(blank=True, default=list, null=True)),
                ('claim_access', models.CharField(blank=True, max_length=255, null=True, verbose_name='Claim Access')),
                ('type_of_claim', models.CharField(blank=True, default='S/A', max_length=255, null=True, verbose_name='Type of Claim')),
                ('claim_status', models.CharField(blank=True, default='En análisis', max_length=255, null=True, verbose_name='Claim Status')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('heading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading')),
                ('subheading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subheading')),
                ('transfer_to_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transfer to company')),
                ('transfer_to_the_consumer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transfer to the consumer')),
                ('conciliation_hearing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conciliation hearing')),
                ('imputation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Imputation')),
                ('resolution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resolution')),
                ('monetary_agreement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Monetary Agreement')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('derived_to_omic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_omic_ive', to='administration.omic')),
                ('derived_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_ive', to='users.account')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
