# Generated by Django 4.2.20 on 2025-04-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claimive'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimer',
            name='between_streets',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Between Streets'),
        ),
        migrations.AddField(
            model_name='claimer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='claimer',
            name='number',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='claimer',
            name='province',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='claimer',
            name='street',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='claimive',
            name='between_streets',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Between Streets'),
        ),
        migrations.AddField(
            model_name='claimive',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='claimive',
            name='number',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='claimive',
            name='province',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='claimive',
            name='street',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='claimive',
            name='establishment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Establishment'),
        ),
        migrations.AlterField(
            model_name='claimive',
            name='other',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='claimive',
            name='type_of_claim',
            field=models.CharField(blank=True, default='IVE', max_length=255, null=True, verbose_name='Type of Claim'),
        ),
    ]
