# Generated by Django 4.2.18 on 2025-02-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_rename_city_name_supplier_city_alter_claimer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimer',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('x', 'X'), ('none', 'Prefiero no decirlo'), ('other', 'Otro'), ('female', 'Femenino')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cuil',
            field=models.CharField(max_length=50, verbose_name='Cuil'),
        ),
    ]
