# Generated by Django 4.2.18 on 2025-02-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claimer_gender_alter_supplier_cuil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimregular',
            old_name='supplier',
            new_name='suppliers',
        ),
        migrations.AlterField(
            model_name='claimer',
            name='gender',
            field=models.CharField(choices=[('female', 'Femenino'), ('x', 'X'), ('none', 'Prefiero no decirlo'), ('other', 'Otro'), ('male', 'Masculino')], max_length=10, verbose_name='Gender'),
        ),
    ]
