# Generated by Django 4.2.18 on 2025-02-24 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_rename_supplier_claimregular_suppliers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='claim',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claimer',
            name='gender',
            field=models.CharField(choices=[('none', 'Prefiero no decirlo'), ('male', 'Masculino'), ('female', 'Femenino'), ('x', 'X'), ('other', 'Otro')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='claimregular',
            name='claimer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claims.claimer'),
        ),
    ]
