# Generated by Django 4.2.18 on 2025-02-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_account_phone'),
        ('claims', '0005_file_claim_alter_claimer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimregular',
            name='derived_to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='users.account'),
        ),
        migrations.AlterField(
            model_name='claimer',
            name='gender',
            field=models.CharField(choices=[('none', 'Prefiero no decirlo'), ('female', 'Femenino'), ('male', 'Masculino'), ('other', 'Otro'), ('x', 'X')], max_length=10, verbose_name='Gender'),
        ),
    ]
