# Generated by Django 4.2.18 on 2025-02-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_account_phone'),
        ('claims', '0006_claimregular_derived_to_user_alter_claimer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimer',
            name='gender',
            field=models.CharField(choices=[('none', 'Prefiero no decirlo'), ('x', 'X'), ('male', 'Masculino'), ('other', 'Otro'), ('female', 'Femenino')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='claimregular',
            name='claim_status',
            field=models.CharField(blank=True, default='En análisis', max_length=255, null=True, verbose_name='Claim Status'),
        ),
        migrations.AlterField(
            model_name='claimregular',
            name='derived_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='users.account'),
        ),
    ]
