# Generated by Django 4.2.18 on 2025-02-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_alter_claimer_gender_alter_claimregular_claim_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimregular',
            name='comments',
        ),
        migrations.AddField(
            model_name='claimregular',
            name='activity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimregular',
            name='problem_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='claimer',
            name='gender',
            field=models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino'), ('x', 'X'), ('other', 'Otro'), ('none', 'Prefiero no decirlo')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='claimregular',
            name='type_of_claim',
            field=models.CharField(blank=True, default='S/A', max_length=255, null=True, verbose_name='Type of Claim'),
        ),
    ]
