# Generated by Django 4.2.16 on 2024-11-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='module',
        ),
        migrations.RemoveField(
            model_name='role',
            name='policies',
        ),
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(to='security.module', verbose_name='Modules'),
        ),
    ]
