# Generated by Django 4.2.20 on 2025-04-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_account_omic'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='users.account'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('pending_review', 'Pendiente Revisión'), ('in_progress', 'En curso'), ('closed', 'Cerrado')], default='pending_review', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='support_level',
            field=models.CharField(blank=True, choices=[('unassigned', 'S/A'), ('n1', 'Nivel 1 (N1)'), ('n2', 'Nivel 2 (N2)'), ('n3', 'Nivel 3 (N3)')], default='unassigned', max_length=30, verbose_name='Support Level'),
        ),
    ]
